# Generated by Django 5.1.1 on 2024-11-10 18:19

import petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='photo_images', validators=[petstagram.photos.validators.validate_file_size]),
        ),
    ]
